language: php

php:
  - 5.3
  - 5.4

before_script:
  - "pear channel-discover pear.phing.info"
  - "pear install --alldeps phing/phing"
  - "phpenv rehash"

script: 
  - "phing lint"
  - "php tests/AllTests.php"